version: "2"
services:
  # Our base OpenKM service is at the localhost. If hosting these on a domain,
  # change the "localhost:8080" to your domain and optionally change the ports.
  # if you are using ingress as a proxy, then you can make the exposed port anything
  # but it must map to 8080 on the container.
  openkm:
    image: openkm/openkm-ce
    container_name: openkm
    ports:
      - 8080:8080
    volumes:
      - ./data:/opt/tomcat/repository
